name: Build and Release ZMQ

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run build script
      run: ./zmq_adapter/build.sh 

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: release-$(date +'%Y%m%d%H%M%S')
        release_name: Release $(date +'%Y%m%d%H%M%S')
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.ADAPTER_GITHUB_TOKEN }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # from the output of create_release step
        asset_path: ./zmq_adapter.zip
        asset_name: zmq_adapter.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.ADAPTER_GITHUB_TOKEN }}
