name: Build and Release ZMQ

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run build script
      run: ./zmq_adapter/build.sh 

    # Calculate the release tag using the date command
    - name: Set release tag
      id: vars
      run: echo "::set-output name=release_tag::release-$(date +'%Y%m%d%H%M%S')"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.vars.outputs.release_tag }}
        release_name: Release ${{ steps.vars.outputs.release_tag }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.ADAPTER_GITHUB_TOKEN }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # from the output of create_release step
        asset_path: ./zmq_adapter/zmq_adapter.zip # adjust the path based on where your build.sh script outputs the .zip file
        asset_name: zmq_adapter.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.ADAPTER_GITHUB_TOKEN }}
